services:
  app:
    container_name: grabber-app_promokodi
    build: ./
    restart: unless-stopped
    ports:
      - 4015:4015
    environment:
      BOT_PREFIX: _promokodi
      TG_ENDPOINT: https://api.telegram.org/bot%s/%s
      APP_PORT: 4015
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_DATABASE: grabber
      PG_HOST: grab_db_promokodi
      PG_PORT: 5432
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/files:/app/files
    networks:
      - malone_4
      - mynet

  db:
    container_name: grab_db_promokodi
    image: postgres:15-alpine
    ports:
      - "5449:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: grabber
    networks:
      - malone_4
      - mynet
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

networks:
  malone_4:
    external: true
  mynet:
    driver: bridge