

services:
  app:
    container_name: grabber-app_india
    build: ./
    restart: unless-stopped
    ports:
      - 4010:4010
    environment:
      BOT_PREFIX: _india
      TG_ENDPOINT: https://api.telegram.org/bot%s/%s
      APP_PORT: 4010
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_DATABASE: grabber
      PG_HOST: grab_db_india
      PG_PORT: 5432
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/files:/app/files
    networks:
      - mynet

  db:
    container_name: grab_db_india
    image: postgres:15-alpine
    ports:
      - "5444:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: grabber
    networks:
      - mynet
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

networks:
  mynet:
    driver: bridge