services:
  app:
    container_name: grabber-app_mishka
    build: ./
    restart: unless-stopped
    ports:
      - 4021:4021
    environment:
      BOT_PREFIX: _mishka
      TG_ENDPOINT: https://api.telegram.org/bot%s/%s
      APP_PORT: 4021
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_DATABASE: grabber
      PG_HOST: grab_db_mishka
      PG_PORT: 5432
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/files:/app/files
    networks:
      - malone_4

  db:
    container_name: grab_db_mishka
    image: postgres:15-alpine
    ports:
      - "5453:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: grabber
    networks:
      - malone_4
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

networks:
  malone_4:
    external: true